# permissions for end users to edit cbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cb-editor-role
rules:
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cbs/status
  verbs:
  - get
