# permissions for end users to view cbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cb-viewer-role
rules:
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cbs/status
  verbs:
  - get
