# permissions for end users to view cis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ci-viewer-role
rules:
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automotive.sig.centos.org
  resources:
  - cis/status
  verbs:
  - get
