---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - get
      - delete
      - list
      - watch
      - patch
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggers
      - triggertemplates
    verbs:
      - create
      - get
      - delete
      - list
      - watch
      - patch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
    verbs:
      - create
      - get
      - delete
      - list
      - watch
      - patch
  ##
  ## Rules for automotive.sig.centos.org/v1, Kind: CI
  ##
  - apiGroups:
      - automotive.sig.centos.org
    resources:
      - cis
      - cis/status
      - cis/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
