apiVersion: automotive.sig.centos.org/v1
kind: ContainerBuild
metadata:
  name: autosd-buildbox
  namespace: autosd
spec:
  git_url: https://gitlab.com/CentOS/automotive/container-images/autosd-buildbox.git
  git_revision: main
  image_name: quay.io/container-ci-test/autosd-buildbox
  local_image: quay.io/container-ci-test/autosd-buildbox:test
  context_dir: .
  containerfile: Containerfile
  test_path: /workspace/source-workspace/Makefile
  test_command: cat
  tests: False
  notify_email: False
