apiVersion: automotive.sig.centos.org/v1
kind: ContainerBuild
metadata:
  name: autosd-buildbox-x86-64-to-aarch64-cross-tools
  namespace: autosd
spec:
  git_url: https://gitlab.com/CentOS/automotive/container-images/autosd-buildbox-x86_64-to-aarch64-cross-tools.git
  git_revision: main
  image_name: quay.io/container-ci-test/autosd-buildbox-x86_64-to-aarch64-cross-tools
  local_image: quay.io/container-ci-test/autosd-buildbox-x86_64-to-aarch64-cross-tools:test
  context_dir: .
  containerfile: Containerfile
  storageclass: efs-sc
  pipeline_name: autosd-buildbox-cross-tools
  test_path: /workspace/source-workspace/Makefile
  test_command: cat
  tests: False
  notify_email: False
