apiVersion: automotive.sig.centos.org/v1
kind: ContainerBuild
metadata:
  name: eclipse-chariott
  namespace: autosd-cb-operator-system
spec:
  git_url: https://gitlab.com/CentOS/automotive/container-images/eclipse-chariott.git
  git_revision: main
  image_name: quay.io/container-ci-test/eclipse-chariott
  local_image: quay.io/container-ci-test/eclipse-chariott:test
  context_dir: .
  containerfile: Containerfile
  storageclass: efs-sc
  test_path: /workspace/source-workspace/Makefile
  test_command: cat
  tests: False
  notify_email: False
