apiVersion: automotive.sig.centos.org/v1
kind: ContainerBuild
metadata:
  name: eclipse-ibeji
  namespace: autosd-cb-operator-system
spec:
  git_url: https://gitlab.com/CentOS/automotive/container-images/eclipse-ibeji.git
  git_revision: main
  image_name: quay.io/container-ci-test/eclipse-ibeji
  local_image: quay.io/container-ci-test/eclipse-ibeji:test
  context_dir: .
  containerfile: Containerfile
  storageclass: efs-sc
  pipeline_name: eclipse-ibeji
  test_path: /workspace/source-workspace/Makefile
  test_command: cat
  namespace: autosd-cb-operator-system
  tests: False
  notify_email: False