---
- block:
  - name: "Create SMTP secret"
    k8s:
      state: present
      definition: "{{ lookup('template', 'smtp-secret.yml.j2') }}"
  #- name: "Create Quay secret"
    #k8s:
      #state: present
      #definition: "{{ lookup('template', 'quay-secret.yml.j2') }}"
  - name: "Apply event-listener"
    k8s:
      state: present
      definition: "{{ lookup('template', 'event-listener.yml.j2') }}"
  - name: "Apply nightly-build"
    k8s:
      state: present
      definition: "{{ lookup('template', 'nightly-build.yml.j2') }}"
  - name: "Apply pipeline"
    k8s:
      state: present
      definition: "{{ lookup('template', 'pipeline.yml.j2') }}"
  - name: "Apply trigger binding"
    k8s:
      state: present
      definition: "{{ lookup('template', 'triggerbinding.yml.j2') }}"
  - name: "Apply trigger template"
    k8s:
      state: present
      definition: "{{ lookup('template', 'triggertemplate.yml.j2') }}"
  - name: "Apply tasks"
    k8s:
      state: present
      definition: "{{ lookup('template', 'tasks.yml.j2') }}"

